### ISSUE TITLE
Nothing on crazymarvin.com/vacation-days/

### ISSUE THREAD

**Issue by comradekingu** [Crazy-Marvin/VacationDays#8]
Not populated yet
Link found in project blurb top right here.

**Comment by CrazyMarvin** [comment]
The landingpage will go online when the app is ready (probably at the end of this year).

**Comment by CrazyMarvin** [comment]
The [homepage](https://crazymarvin.com/vacation-days/) is active now. 

The release of Vacation Days on F-Droid and Google Play is under review at the moment so that the links to F-Droid and Google Play will work soon too.

Please let me know if you find any other dead links. Thanks for your help! 👍

**Comment by CrazyMarvin** [comment]
Google just approved the app.
I suppose F-Droid will follow soon.
